### ISSUE TITLE
Docker构建的镜像无法使用远程访问，如何设置 GRADIO SERVER share=True

### ISSUE THREAD

**Issue by IAMJOYBO** [FunAudioLLM/SenseVoice#210]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

![Image](https://github.com/user-attachments/assets/abab3b1e-3815-4be0-9afa-27a2caf446e2)

![Image](https://github.com/user-attachments/assets/d4346e38-3c6c-4e98-a58c-585f78cf5b33)

### To Reproduce

```Dockerfile
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 50000
ENV TZ=Asia/Shanghai

RUN mkdir -p /app
WORKDIR /app
RUN apt update && apt install -y wget curl net-tools tree git git-lfs 

RUN git clone https://github.com/FunAudioLLM/SenseVoice.git
WORKDIR /app/SenseVoice
RUN pip install -r requirements.txt

RUN rm -rf /var/lib/apt/lists/*

CMD ["python", "webui.py"]
```

```yaml
services:
  sensevoice:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/sensevoice:v2025.04.13-action
    container_name: sensevoice
    hostname: sensevoice
    environment:
      - TZ=Asia/Shanghai
      - HF_HOME=/app
      - MODELSCOPE_CACHE=/app
      - GRADIO_SERVER_NAME="0.0.0.0"
      # - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./:/app/sensevoice
      - O:\Hub\modelscope\hub\models:/app/models
      - O:\Hub\huggingface:/app/huggingface
      - O:\Hub\modelscope:/app/modelscope
    ports:
      - "7860:7860"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - sensevoice
    entrypoint: ["python", "webui.py", "--listen"]

networks:
  sensevoice:
    driver: bridge
    name: sensevoice
```

#### Code sample

https://github.com/IAMJOYBO/sensevoice

### Environment

```Dockerfile
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 50000
ENV TZ=Asia/Shanghai

RUN mkdir -p /app
WORKDIR /app
RUN apt update && apt install -y wget curl net-tools tree git git-lfs 

RUN git clone https://github.com/FunAudioLLM/SenseVoice.git
WORKDIR /app/SenseVoice
RUN pip install -r requirements.txt

RUN rm -rf /var/lib/apt/lists/*

CMD ["python", "webui.py"]
```
